### ISSUE TITLE
guidance

### ISSUE THREAD

**Issue by openye** [JacobHDahl/TTK4190#1]
Hello, excuse you, I want to ask you if there is any ILOS related code, especially want to know this knowledge, thank you

**Comment by openye** [comment]
what is MSS?

**Comment by JacobHDahl** [comment]
There is some crude, slapped together ILOS code in the guidance.m function. MSS is the Marine Systems Simulator (not mine), but you can find it here: https://github.com/cybergalactic/MSS

**Comment by openye** [comment]
Thank you very much for your help. ILOS is now a parameter path. How should this parameter path be combined?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JacobHDahl"<notifications@github.com&gt;; 
发送时间: 2020年11月21日(星期六) 晚上8:49
收件人: "JacobHDahl/TTK4190"<TTK4190@noreply.github.com&gt;; 
抄送: "1183832562"<1183832562@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [JacobHDahl/TTK4190] guidance (#1)





 
There is some crude, slapped together ILOS code in the guidance.m function. MSS is the Marine Systems Simulator (not mine), but you can find it here: https://github.com/cybergalactic/MSS

**Comment by openye** [comment]
Is this function code in the MSS toolbox?






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JacobHDahl"<notifications@github.com&gt;; 
发送时间: 2020年11月21日(星期六) 晚上8:49
收件人: "JacobHDahl/TTK4190"<TTK4190@noreply.github.com&gt;; 
抄送: "1183832562"<1183832562@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [JacobHDahl/TTK4190] guidance (#1)





 
There is some crude, slapped together ILOS code in the guidance.m function. MSS is the Marine Systems Simulator (not mine), but you can find it here: https://github.com/cybergalactic/MSS

**Comment by openye** [comment]
This is the simulation effect of the function I wrote myself. Can you give me some guidance?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JacobHDahl"<notifications@github.com&gt;; 
发送时间: 2020年11月21日(星期六) 晚上8:49
收件人: "JacobHDahl/TTK4190"<TTK4190@noreply.github.com&gt;; 
抄送: "1183832562"<1183832562@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [JacobHDahl/TTK4190] guidance (#1)





 
Closed #1.
